### ISSUE TITLE
hello_gong and hello_ack should use public midi api instead of internal midi api 

### ISSUE THREAD

**Issue by ngwese** [monome/dust#122]
these lines handle midi the old way before the mid level api was put in place. this script should be updated to use the public api as demonstrated in in `earthsea`

problem code:
https://github.com/monome/dust/blob/master/scripts/jah/hello_gong.lua#L166-L212

/cc @antonhornquist, @artfwo

**Comment by antonhornquist** [comment]
thanks. will fix. same goes for hello_ack.
