### ISSUE TITLE
EMB Loops script fails reliably

### ISSUE THREAD

**Issue by lazzarello** [monome/dust#257]
Loading the script in [scripts/emb/loops.lua](https://github.com/monome/dust/tree/master/scripts/emb) puts the device in a state where the OLED says "no parameters" and what sounds like a somewhat short buffer size that is looping whatever sound is coming in the input. The first key does not exit menu mode.

It [looks like the script is asking for key 2](https://github.com/monome/dust/blob/master/scripts/emb/loops.lua#L126) to control starting and stopping a metronome.

The the failure is kind of interesting since it produces somewhat pleasant noise based on most inputs, though the controls make this script appear as if the device is broken.

Running dust from release 181101. Not tracking master branch in git.

**Comment by catfact** [comment]
everything in `emb` is for internal testing and itsn't meant to be useful.

**Comment by catfact** [comment]
deleted `loops.lua`

**Comment by lazzarello** [comment]
Lol. It does make some v nice noise  ;)

**Comment by catfact** [comment]
it is/was always in there as the most fundamental test that SoftCut ugen is present and basically working.
