### ISSUE TITLE
ack: ADSR envelope

### ISSUE THREAD

**Issue by audionerd** [monome/dust#288]
i'd like to sustain notes with ack.

maybe with a new argument to the SynthDef:
```SuperCollider
playbackMode = 0 // 0 for one-shot, 1 for ADSR
```

so that existing scripts would not have to change.

when set to `1` for ADSR, it would enable more arguments for the envelope:
```SuperCollider
volumeEnvDecay = 0.3
volumeEnvSustainLevel = 0.5
volumeEnvPeakLevel = 1
```

and maybe even
```SuperCollider
volumeEnvCurve = -4
volumeEnvBias = 0
```

when gate is `0`, the envelope begins to close.

i have a prototype of this working for the Engine_Ack SynthDefs, and could submit a PR.

is there any interest in this feature for ack? or should it be part of a new engine?

**Comment by antonhornquist** [comment]
FWIW I have a separate engine for this, but its not pushed yet (a poly Ack thing).

**Comment by audionerd** [comment]
Cool. Looking forward to your new engine.

**Comment by notjustmat** [comment]
@audionerd any chance you still have this working somewhere? There has been some interest expressed over on lines :)

**Comment by audionerd** [comment]
@notjustmat I only prototyped a change to the SynthDefs in an .scd, I never actually updated Engine_Ack.

**Comment by notjustmat** [comment]
Ah, sorry for the misunderstanding! I guess it is about time I get acquainted with the SC side of Norns :)
