### ISSUE TITLE
"ack" engine - simple sample player

### ISSUE THREAD

**Issue by tehn** [monome/dust#3]
- sample select
- one-shot (trig)
- loop points
- playback speed (w/ reverse)
- gain
- volume envelope (# points? at least AR)
- filter cutoff, res, mode
- filter cutoff envelope

8 channels is fine as a default. each index has each of the above params

ie

e.trig(n) where n is the index, triggers envelopes and loop start
e.speed(n,-1.0) where n is index, -1.0 is reverse 1x

envelopes and loop points in ms is fine? number of points for envelope? (can this be variable/dynamic?)

bonus points:

- slew time for speed, volume, cutoff, res
- shaper/overdrive per voice
- loop windowing toggle
- aux send master delay, aux send to master reverb

up for suggestions on the engine name, "ack" just references the early akai sampler inspiration

**Comment by antonhornquist** [comment]
I will split up remaining work in smaller issues
