### ISSUE TITLE
Update dust repo to 2.0

### ISSUE THREAD

**Issue by okyeron** [monome/dust#301]
At the moment the dust repo is still structured for 1.0

Could 1.0 be pushed to a separate branch and 2.0 structure added for ease of pulling that directory structure (for building on RasPi)?

**Comment by simonvanderveldt** [comment]
Dust/this repo is no longer being used. The `~/dust` directory that's on device is just a directory not a clone of this repo :)

Pretty much all the contents from this repo have already been moved to a new home, although some things might still need to be moved (everything in the `audio` directory it seems and maybe some of the psets, I'm not sure). Once that's done I expect this repo will be archived.

**Comment by catfact** [comment]
one thing i thought of is converting this into a simple dcollection of known norns projects included as submodules. maybe useful for testing intercompatibility and providing a one-stop 'kitchen sink' installation.
