### ISSUE TITLE
dust does not say whose code should live here

### ISSUE THREAD

**Issue by nf** [monome/dust#92]
What's the intention of the dust repository? Is it for everyone? Just the people at monome? Is there a bar for inclusion.

Put another way, if I start building norns things, would I send a pull request to add them to `scripts/nf` in this repository?

It would be good to make this clear in the README.

**Comment by tehn** [comment]
indeed-- i'll add a contributions text in the readme. in short, yes, we'd love to add more scripts. we'll set a criteria for inclusion and then PR's will be accepted.

more tomorrow.

**Comment by pq** [comment]
was this sufficiently addressed w/ https://github.com/monome/dust/commit/75b8dd7b86591ce014dd8789cd59ea09e6dc8e3d?

maybe can we close?
